package catalog

import (
	"encoding/json"
	// The blank embed import keeps go:embed available even though this
	// file only declares the variable.
	_ "embed"
	"fmt"
)

// The snapshot compiled into the binary so scans work with no network at
// all. Regenerated by "overwater catalog build"; CI fails when it drifts
// from the YAML entries.
//
//go:embed catalog.json
var embeddedJSON []byte

// Embedded parses and validates the built-in snapshot.
func Embedded() (*Catalog, error) {
	var c Catalog
	if err := json.Unmarshal(embeddedJSON, &c); err != nil {
		return nil, fmt.Errorf("embedded catalog: %w", err)
	}
	if err := c.Validate(); err != nil {
		return nil, fmt.Errorf("embedded catalog: %w", err)
	}
	return &c, nil
}

// EmbeddedJSON exposes the raw snapshot bytes for the sync test.
func EmbeddedJSON() []byte {
	return embeddedJSON
}
