package evalgen

// The templates are plain Python on purpose: readable before running,
// editable after generating, no framework. Exact match agreement is
// strict, and for the structured task classes these findings target,
// strict is the point.

const anthropicTemplate = `#!/usr/bin/env python3
# Generated by overwater for {{RULE}} at {{SITE}}.
# Compares {{CURRENT}} against {{CANDIDATE}} on your own prompts.
# Tripwire: {{TRIPWIRE}}
#
# This script calls the Anthropic API with your key. overwater itself
# never calls any model API; you run this, on your terms.
#
# Usage:
#   pip install anthropic
#   export ANTHROPIC_API_KEY=your-key
#   python3 {{SCRIPT}} prompts.jsonl
#
# prompts.jsonl holds one JSON object per line:
#   {"prompt": "the user message", "system": "optional system prompt"}
# Use real production prompts; invented ones prove nothing.

import json
import sys

import anthropic

CURRENT = "{{CURRENT}}"
CANDIDATE = "{{CANDIDATE}}"


def ask(client, model, system, prompt):
    kwargs = {
        "model": model,
        "max_tokens": 512,
        "messages": [{"role": "user", "content": prompt}],
    }
    if system:
        kwargs["system"] = system
    message = client.messages.create(**kwargs)
    parts = []
    for block in message.content:
        text = getattr(block, "text", None)
        if text:
            parts.append(text)
    return "\n".join(parts).strip()


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: python3 " + sys.argv[0] + " prompts.jsonl")
    rows = []
    with open(sys.argv[1]) as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    if not rows:
        sys.exit("no prompts in " + sys.argv[1])
    client = anthropic.Anthropic()
    agree = 0
    for i, row in enumerate(rows):
        a = ask(client, CURRENT, row.get("system", ""), row["prompt"])
        b = ask(client, CANDIDATE, row.get("system", ""), row["prompt"])
        if a == b:
            agree += 1
        else:
            print("prompt %d disagrees:" % i)
            print("  %s: %r" % (CURRENT, a[:160]))
            print("  %s: %r" % (CANDIDATE, b[:160]))
    pct = 100.0 * agree / len(rows)
    print("agreement: %d/%d (%.1f%%)" % (agree, len(rows), pct))
    print("tripwire: {{TRIPWIRE}}")


if __name__ == "__main__":
    main()
`

const openaiTemplate = `#!/usr/bin/env python3
# Generated by overwater for {{RULE}} at {{SITE}}.
# Compares {{CURRENT}} against {{CANDIDATE}} on your own prompts.
# Tripwire: {{TRIPWIRE}}
#
# This script calls the OpenAI API with your key. overwater itself
# never calls any model API; you run this, on your terms.
#
# Usage:
#   pip install openai
#   export OPENAI_API_KEY=your-key
#   python3 {{SCRIPT}} prompts.jsonl
#
# prompts.jsonl holds one JSON object per line:
#   {"prompt": "the user message", "system": "optional system prompt"}
# Use real production prompts; invented ones prove nothing.

import json
import sys

from openai import OpenAI

CURRENT = "{{CURRENT}}"
CANDIDATE = "{{CANDIDATE}}"


def ask(client, model, system, prompt):
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})
    resp = client.chat.completions.create(
        model=model,
        max_completion_tokens=512,
        messages=messages,
    )
    return (resp.choices[0].message.content or "").strip()


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: python3 " + sys.argv[0] + " prompts.jsonl")
    rows = []
    with open(sys.argv[1]) as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    if not rows:
        sys.exit("no prompts in " + sys.argv[1])
    client = OpenAI()
    agree = 0
    for i, row in enumerate(rows):
        a = ask(client, CURRENT, row.get("system", ""), row["prompt"])
        b = ask(client, CANDIDATE, row.get("system", ""), row["prompt"])
        if a == b:
            agree += 1
        else:
            print("prompt %d disagrees:" % i)
            print("  %s: %r" % (CURRENT, a[:160]))
            print("  %s: %r" % (CANDIDATE, b[:160]))
    pct = 100.0 * agree / len(rows)
    print("agreement: %d/%d (%.1f%%)" % (agree, len(rows), pct))
    print("tripwire: {{TRIPWIRE}}")


if __name__ == "__main__":
    main()
`

const embeddingTemplate = `#!/usr/bin/env python3
# Generated by overwater for {{RULE}} at {{SITE}}.
# Compares {{CURRENT}} against {{CANDIDATE}} as retrieval embeddings.
# Tripwire: {{TRIPWIRE}}
#
# Different embedding models live in different vector spaces, so their
# vectors cannot be compared directly. Behavior can be: embed every
# text with both models and check whether each text's nearest neighbor
# stays the same. Ten or more varied texts make the number meaningful.
#
# Usage:
#   pip install openai
#   export OPENAI_API_KEY=your-key
#   python3 {{SCRIPT}} prompts.jsonl
#
# prompts.jsonl holds one JSON object per line: {"prompt": "chunk text"}

import json
import math
import sys

from openai import OpenAI

CURRENT = "{{CURRENT}}"
CANDIDATE = "{{CANDIDATE}}"


def embed_all(client, model, texts):
    resp = client.embeddings.create(model=model, input=texts)
    return [item.embedding for item in resp.data]


def cosine(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    if not na or not nb:
        return 0.0
    return dot / (na * nb)


def nearest(i, vectors):
    best, score = -1, -2.0
    for j, v in enumerate(vectors):
        if j == i:
            continue
        s = cosine(vectors[i], v)
        if s > score:
            best, score = j, s
    return best


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: python3 " + sys.argv[0] + " prompts.jsonl")
    texts = []
    with open(sys.argv[1]) as handle:
        for line in handle:
            if line.strip():
                texts.append(json.loads(line)["prompt"])
    if len(texts) < 3:
        sys.exit("need at least 3 texts to compare neighborhoods")
    client = OpenAI()
    current = embed_all(client, CURRENT, texts)
    candidate = embed_all(client, CANDIDATE, texts)
    agree = 0
    for i in range(len(texts)):
        if nearest(i, current) == nearest(i, candidate):
            agree += 1
    pct = 100.0 * agree / len(texts)
    print("nearest neighbor agreement: %d/%d (%.1f%%)" % (agree, len(texts), pct))
    print("tripwire: {{TRIPWIRE}}")


if __name__ == "__main__":
    main()
`
