# Generated by tools/sync-manifests; edit the template, not this file.
class Overwater < Formula
  desc "Flag LLM call sites that use more model than the task needs"
  homepage "https://github.com/MithrilBytes/overwater"
  version "2.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.6.0/overwater_darwin_arm64"
      sha256 "38946138e22cc3966f6d9e29548eac80ae735efafc4f37cfbeeea1d50315746e"
    end
    on_intel do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.6.0/overwater_darwin_amd64"
      sha256 "714e483a7e2704b66e588a69aa33ff127e0e446ef93776a6be6e53c71cbb6b57"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.6.0/overwater_linux_arm64"
      sha256 "692be3eb430e0ceb14929e87be82d7c56bdbfa1e1fdea453faa0c78e464d3b74"
    end
    on_intel do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.6.0/overwater_linux_amd64"
      sha256 "617303809a4c1eb017ff3dc3cbc192007fa1b698af67823e2859dab4066a004e"
    end
  end

  def install
    bin.install Dir["overwater_*"].first => "overwater"
  end

  test do
    assert_match "overwater v2.6.0", shell_output("#{bin}/overwater version")
  end
end
