# Generated by tools/sync-manifests; edit the template, not this file.
class Overwater < Formula
  desc "Flag LLM call sites that use more model than the task needs"
  homepage "https://github.com/MithrilBytes/overwater"
  version "2.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.1.0/overwater_darwin_arm64"
      sha256 "b8dc63a82909ddff18ab71d71ce7ecdc0bb9473c21a421c54c12a60cdd8539a6"
    end
    on_intel do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.1.0/overwater_darwin_amd64"
      sha256 "3cc58cec3735a6337901130e0bfbaf4826fa330949b8ff3ac1635ce88671cad9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.1.0/overwater_linux_arm64"
      sha256 "c8654699684db322bf89d201a00d7ab181079fc0e80a136e16052084ba3141e5"
    end
    on_intel do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.1.0/overwater_linux_amd64"
      sha256 "2e36f5c6ebd0c9de91c16b5ec0d48023a1d393a49fa297086f44f7b4728553ba"
    end
  end

  def install
    bin.install Dir["overwater_*"].first => "overwater"
  end

  test do
    assert_match "overwater v2.1.0", shell_output("#{bin}/overwater version")
  end
end
