# Generated by tools/sync-manifests; edit the template, not this file.
class Overwater < Formula
  desc "Flag LLM call sites that use more model than the task needs"
  homepage "https://github.com/MithrilBytes/overwater"
  version "2.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.9.0/overwater_darwin_arm64"
      sha256 "dbbc1fd7df819758529602960d1b3bb0e234fce3dfe54f1deb1781a645462f28"
    end
    on_intel do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.9.0/overwater_darwin_amd64"
      sha256 "eb61dd4db87975d8d1f54e646e624ab8c3cd642f5bc1d9065963e82ee48f31a7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.9.0/overwater_linux_arm64"
      sha256 "6a736da8c333de6344a76ea3435d91cd0a460b6ea6c165ee3f40cdf92d18b58e"
    end
    on_intel do
      url "https://github.com/MithrilBytes/overwater/releases/download/v2.9.0/overwater_linux_amd64"
      sha256 "c8f16554b2e7c4126134d74adc41af1dfbf1ec126e8861f282315e4fdd22da53"
    end
  end

  def install
    bin.install Dir["overwater_*"].first => "overwater"
  end

  test do
    assert_match "overwater v2.9.0", shell_output("#{bin}/overwater version")
  end
end
