package packaging

import "text/template"

// Manifest paths, relative to the repository root.
const (
	FormulaPath        = "Formula/overwater.rb"
	ScoopPath          = "scoop/overwater.json"
	WingetVersionPath  = "winget/MithrilBytes.Overwater.yaml"
	WingetInstallPath  = "winget/MithrilBytes.Overwater.installer.yaml"
	WingetLocalePath   = "winget/MithrilBytes.Overwater.locale.en-US.yaml"
	FlakePath          = "flake.nix"
	wingetManifestVer  = "1.6.0"
	generatedByComment = "tools/sync-manifests"
)

var manifests = map[string]*template.Template{
	FormulaPath:       template.Must(template.New(FormulaPath).Parse(formulaTemplate)),
	ScoopPath:         template.Must(template.New(ScoopPath).Parse(scoopTemplate)),
	WingetVersionPath: template.Must(template.New(WingetVersionPath).Parse(wingetVersionTemplate)),
	WingetInstallPath: template.Must(template.New(WingetInstallPath).Parse(wingetInstallerTemplate)),
	WingetLocalePath:  template.Must(template.New(WingetLocalePath).Parse(wingetLocaleTemplate)),
}

const formulaTemplate = `# Generated by ` + generatedByComment + `; edit the template, not this file.
class Overwater < Formula
  desc "{{.Description}}"
  homepage "{{.Repo}}"
  version "{{.Version}}"
  license "MIT"

  on_macos do
    on_arm do
      url "{{.Repo}}/releases/download/{{.Tag}}/` + assetDarwinARM64 + `"
      sha256 "{{.DarwinARM64}}"
    end
    on_intel do
      url "{{.Repo}}/releases/download/{{.Tag}}/` + assetDarwinAMD64 + `"
      sha256 "{{.DarwinAMD64}}"
    end
  end

  on_linux do
    on_arm do
      url "{{.Repo}}/releases/download/{{.Tag}}/` + assetLinuxARM64 + `"
      sha256 "{{.LinuxARM64}}"
    end
    on_intel do
      url "{{.Repo}}/releases/download/{{.Tag}}/` + assetLinuxAMD64 + `"
      sha256 "{{.LinuxAMD64}}"
    end
  end

  def install
    bin.install Dir["overwater_*"].first => "overwater"
  end

  test do
    assert_match "overwater {{.Tag}}", shell_output("#{bin}/overwater version")
  end
end
`

const scoopTemplate = `{
    "##": "Generated by ` + generatedByComment + `; edit the template, not this file.",
    "version": "{{.Version}}",
    "description": "{{.Description}}",
    "homepage": "{{.Repo}}",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "{{.Repo}}/releases/download/{{.Tag}}/` + assetWindowsAMD64 + `#/overwater.exe",
            "hash": "{{.WindowsAMD64}}"
        }
    },
    "bin": "overwater.exe",
    "checkver": {
        "github": "{{.Repo}}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "{{.Repo}}/releases/download/v$version/` + assetWindowsAMD64 + `#/overwater.exe"
            }
        },
        "hash": {
            "url": "{{.Repo}}/releases/download/v$version/SHA256SUMS"
        }
    }
}
`

const wingetVersionTemplate = `# Generated by ` + generatedByComment + `; edit the template, not this file.
PackageIdentifier: MithrilBytes.Overwater
PackageVersion: {{.Version}}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: ` + wingetManifestVer + `
`

const wingetInstallerTemplate = `# Generated by ` + generatedByComment + `; edit the template, not this file.
PackageIdentifier: MithrilBytes.Overwater
PackageVersion: {{.Version}}
InstallerType: portable
Commands:
  - overwater
ReleaseNotesUrl: {{.Repo}}/releases/tag/{{.Tag}}
Installers:
  - Architecture: x64
    InstallerUrl: {{.Repo}}/releases/download/{{.Tag}}/` + assetWindowsAMD64 + `
    InstallerSha256: {{.WindowsUpper}}
ManifestType: installer
ManifestVersion: ` + wingetManifestVer + `
`

const wingetLocaleTemplate = `# Generated by ` + generatedByComment + `; edit the template, not this file.
PackageIdentifier: MithrilBytes.Overwater
PackageVersion: {{.Version}}
PackageLocale: en-US
Publisher: MithrilBytes
PublisherUrl: {{.Repo}}
PackageName: overwater
PackageUrl: {{.Repo}}
License: MIT
LicenseUrl: {{.Repo}}/blob/main/LICENSE
ShortDescription: {{.Description}}
Tags:
  - cost
  - llm
  - static-analysis
ManifestType: defaultLocale
ManifestVersion: ` + wingetManifestVer + `
`
